# Generated by Django 4.2.6 on 2023-11-03 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
